config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :backoffice do
    resources :case_studies, path: 'case-studies' do
      resources :pages, except: [:index, :show]
      resources :select_type, only: [:index]
      post 'duplicate', on: :member
    end

    resources :users, except: [:show]
    resources :organizations, except: [:show]

    resources :data_layers, path: "data-layers", only: [:destroy, :show]
    root 'case_studies#index', as: 'dashboard'
  end

  resources :case_studies, only: [:index, :show], param: :slug, path: 'case-studies' do
    get 'preview', on: :member
  end

  resources :tags, defaults: { format: 'json' }
  get '/tags', to: 'tags#index'

  resources :contact_form, only: [:create], path: "contact-form", defaults: { format: 'json' }

  get '/cases', to: redirect('/#cases')
  get '/contact-form', to: redirect('/#contact-form')

  root 'landing#index', as: 'root'

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  layout "landing"

  def index
    @contact_form = ContactForm.new
    @tags = Tag.all
    @case_studies = CaseStudy.published.limit(9)

    gon.case_studies = ActiveModel::ArraySerializer.
      new(@case_studies, each_serializer: CaseStudySerializer).to_json
    gon.cartodb_user = ENV["CDB_USERNAME"]
  end
end

app/views/landing/_contact_form.html.slim
section#contact-form.contact-form-container
  .wrap: .row
    .grid-xs-12.contact-form
      h2.title = t('contact')
      .form
        = simple_form_for @contact_form, url: contact_form_index_path, class: 'contact-form', remote: true do |f|
        
          .row.form-row
            .grid-xs-12.grid-sm-6
              = f.input :email, required: true, label: "Email address", placeholder: "example@email.com"
            .grid-xs-12.grid-sm-6
              = f.input :name, required: true, label: "Your name", placeholder: "Your name here"
              
          .row.form-row
            .grid-xs-12
              = f.input :content, required: true, label: "Message", placeholder: "Write your message here"

          = f.button :submit, "Send", class: 'button btn -landing -inv'
      .feedback._hidden
        .feedback-content
        button class="btn button -landing -inv reset" Ok

app/views/landing/_footer.html.slim
footer.footer
  .pre-footer
    .logo
  .wrap
    .row
      .grid-xs-7.grid-md-7.column
        nav.nav role="navigation"
          svg.icon.icon-eoworld-logo
            use xlink:href="#icon-eoworld-logo"
          ul
            li = link_to t('case_studies'), "/#cases", class:'smooth-link'
            li = link_to t('contact'), "/#contact-form", class:'smooth-link'
      .grid-xs-12.grid-md-5.column.partnerts
          span.title =t('parnertship_convened')
          .partner-list
            = link_to 'http://www.esa.int/ESA', class: "item", target: "_blank" do
              svg.icon.icon-esa-logo
                use xlink:href="#icon-esa-logo"
            = link_to 'http://www.esa.int/ESA', class: "item", target: "_blank" do
              svg.icon.icon-esa-logo
                use xlink:href="#icon-esa-logo"
  .copyright
    span © 2013 - 2015 · Terms of Service · European Space Agency and World Bank Group

app/views/landing/index.html.slim
.l-content
  .map-container._center
    #map.map
    .wrap._relative
      button.btn.-landing.-alt.close-explore-btn.toggle-explore =t('close_explore_map')
    
  #banner.banner
    .title 
      h1 =t('earth_observation')
    .title
      h1 =t('sustainable_development')
    .link
      button.btn.-landing.toggle-explore =t('explore_map')

  section#cases.cases
    .wrap: .row._right
      .tags-filter
        span.select2-title = t('filter_cases_by')
        select#searchBox.select2 style="width: 10rem"
          option
          - @tags.each do |t|
            option value="#{t.name}" =t.name
    .wrap
      #casesArticles.row._is-loading
        - @case_studies.each do |c|
          article.grid-xs-12.grid-sm-6.grid-md-4.case._is-loading.-clickable id=("case-#{c.id}")
            - style = c.cover_image? ? "background-image: url(#{c.cover_image.url(:medium)})" : ''
            =link_to case_study_path(c.slug), style: style
              .caption
                h2 =c.title

  = render('contact_form');
  = render('footer');