config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :backoffice do
    resources :case_studies, path: 'case-studies' do
      resources :pages, except: [:index, :show]
      resources :select_type, only: [:index]
      post 'duplicate', on: :member
    end

    resources :users, except: [:show]
    resources :organizations, except: [:show]

    resources :data_layers, path: "data-layers", only: [:destroy, :show]
    root 'case_studies#index', as: 'dashboard'
  end

  resources :case_studies, only: [:index, :show], param: :slug, path: 'case-studies' do
    get 'preview', on: :member
  end

  resources :tags, defaults: { format: 'json' }
  get '/tags', to: 'tags#index'

  resources :contact_form, only: [:create], path: "contact-form", defaults: { format: 'json' }

  get '/cases', to: redirect('/#cases')
  get '/contact-form', to: redirect('/#contact-form')

  root 'landing#index', as: 'root'

end

app/controllers/backoffice/case_studies_controller.rb
class Backoffice::CaseStudiesController < BackofficeController

  before_action :set_case_study, only: [:show, :edit, :update, :destroy]
  before_action :set_existing_contacts, only: [:new, :edit]
  before_action :restrict_access!, only: [:edit, :update, :destroy]

  def index
    @case_studies = if current_user.is_admin?
                      CaseStudy.all
                    elsif current_user.organization.nil?
                      CaseStudy.where(organization_id: nil)
                    else
                      current_user.organization.try(:case_studies) || []
                    end
  end

  def show
    redirect_to edit_backoffice_case_study_path(@case_study)
  end

  def new
    @case_study = CaseStudy.new
    @contacts = @case_study.contacts.build
  end

  def edit
    @contacts = @case_study.contacts.presence || @case_study.contacts.build
  end

  def create
    @case_study = CaseStudy.new(case_studies_params)
    if @case_study.save
      redirect_to edit_backoffice_case_study_path(@case_study),
        notice: 'Case study created successfully.'
    else
      set_existing_contacts
      render :new
    end
  end

  def update
    if @case_study.update(case_studies_params)
      redirect_to [:backoffice, @case_study],
        notice: 'Case study updated successfully.'
    else
      set_existing_contacts
      render :edit
    end
  end

  def destroy
    @case_study.destroy
    redirect_to backoffice_case_studies_path,
      notice: 'Case study deleted successfully.'
  end

  def duplicate
    @case_study = CaseStudy.clone(params[:id])
    if @case_study.save
      redirect_to edit_backoffice_case_study_path(@case_study),
        notice: 'Case study duplicated successfully.'
    else
      redirect_to request.referrer || backoffice_dashboard_path,
        alert: 'Case study duplication failed.'
    end
  end

  private

    def set_case_study
      @case_study = CaseStudy.find(params[:id])
    end

    def set_existing_contacts
      @existing_contacts = Contact.all.where.not(logo_file_name: nil).to_a
      @existing_contacts.uniq!{|c| c.logo_file_name}
    end

    def case_studies_params
      params.require(:case_study).permit(
        :title,
        :slug,
        :description,
        :published,
        :lat,
        :lng,
        :template,
        :cover_image,
        :tag_list,
        :delete_image,
        contacts_attributes: [:id, :body, :logo, :website, :_destroy,
          :delete_image, :logo_from_contact_id]
      )
    end

    def restrict_access!
      unless current_user.is_admin? || current_user.can_manage?(@case_study)
        redirect_to backoffice_case_studies_path,
          error: "You can only manage your Organization's case studies."
      end
    end

end

app/controllers/backoffice/data_layers_controller.rb
class Backoffice::DataLayersController < BackofficeController

  before_action :set_data_layer, only: [:show, :destroy]

  respond_to :json

  def show
    body = @data_layer ||
      { error:'400', msg: 'You need to provide an id', data_layer:{}}
    render json: body
  end

  def destroy
    @page = @data_layer.page
    @data_layer.destroy
    respond_to do |format|
      format.json { render json: true }
      format.html { redirect_to edit_backoffice_case_study_page_path(@page.case_study, @page) }
    end
  end


  private

  def set_data_layer
    @data_layer = DataLayer.find(params[:id])
  end
end

app/controllers/backoffice/organizations_controller.rb
class Backoffice::OrganizationsController < BackofficeController

  before_action :set_organization, only: [:edit, :update, :destroy]
  before_action :authorize_admins!

  def index
    @organizations = Organization.all
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organizations_params)
    if @organization.save
      redirect_to backoffice_organizations_path,
        notice: 'Organization created successfully'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @organization.update(organizations_params)
      redirect_to backoffice_organizations_path,
        notice: 'Organization updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @organization.destroy
    redirect_to backoffice_organizations_path,
      notice: 'Organization deleted successfully'
  end

  private

  def set_organization
    @organization = Organization.find(params[:id])
  end

  def organizations_params
    params.require(:organization).permit(:name)
  end
end

app/controllers/backoffice/pages_controller.rb
class Backoffice::PagesController < BackofficeController

  before_action :set_case_study, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_page, only: [:edit, :update, :destroy]
  before_action :set_charts, only: [:new, :edit]

  def new
    @page = @case_study.pages.new(page_type: params[:type])
    @page.data_layers.build
  end

  def create
    @page = @case_study.pages.new(page_params)
    if @page.save

      upload_pending_files

      redirect_to edit_backoffice_case_study_page_path(
        @case_study, @page,
          type: @page.page_type,
          shapefile: nil
      ), notice: 'Page created successfully.'
    else
      @page.data_layers.build if @page.data_layers.empty?
      set_charts
      render :new
    end
  end

  def edit
    gon.cartodb_user = ENV["CDB_USERNAME"]
    gon.case_study = @case_study.to_json
    gon.page = @page.to_json(include: :data_layers)
  end

  def update
    if @page.update(page_params)

      upload_pending_files

      redirect_to edit_backoffice_case_study_page_path(
        @case_study, @page, type: @page.page_type
      ), notice: 'Page updated successfully.'
    else
      @page.data_layers.build if @page.data_layers.empty?
      gon.cartodb_user = ENV["CDB_USERNAME"]
      gon.case_study = @case_study.to_json
      gon.page = @page.to_json(include: :data_layers)
      set_charts
      render :edit
    end
  end

  def destroy
    @page.destroy
    redirect_to edit_backoffice_case_study_path(@case_study),
      notice: 'Page deleted successfully.'
  end

  private

    def upload_pending_files
      @page.data_layers.each do |d|
        Resque.enqueue(CartoDbImporter, d.id) if d.import_status == ImportStatus::PENDING
      end
    end

    def set_case_study
      @case_study = CaseStudy.find(params[:case_study_id])
    end

    def set_page
      @page = Page.find(params[:id])
    end

    def set_charts
      @charts = Chart.all
    end

    def page_params
      params.require(:page).permit(
        :title,
        :basemap,
        :basemap_url,
        :body,
        :background,
        :color_palette,
        :custom_basemap,
        :page_type,
        :chart_type_list,
        :case_study_id,
        :column_selected,
        :delete_image,
        data_layers_attributes: [
          :id,
          :table_name,
          :year,
          :shapefile,
          :layer_column,
          :layer_column_alias,
          :raster_color_input,
          :raster_type,
          :raster_categories,
          :custom_columns_colors
        ],
        interest_points_attributes: [:id, :name, :lat, :lng, :radius, :_destroy, :description],
        chart_ids: []
      )
    end

end

app/controllers/backoffice/select_type_controller.rb
class Backoffice::SelectTypeController < BackofficeController

  def index
    @case_study = CaseStudy.find(params[:case_study_id])
  end

end

app/controllers/backoffice/users_controller.rb
class Backoffice::UsersController < BackofficeController

  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :set_organizations, only: [:edit, :new]
  before_action :set_change_pwd, only: [:edit, :update]
  before_action :restrict_access!, only: [:edit, :update, :destroy]

  def index
    @users = User.all.order(:email)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to backoffice_users_path,
        notice: 'User created successfully.'
    else
      set_organizations
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to backoffice_users_path,
        notice: 'User updated successfully.'
    else
      set_organizations
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to backoffice_users_path, notice: 'Page deleted successfully.'
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit!
    end

    def set_organizations
      @organizations = Organization.all
    end

    def set_change_pwd
      @change_pwd = params[:change_pwd].presence || false
    end

    def restrict_access!
      unless current_user.is_admin? || current_user == @user
        redirect_to backoffice_users_path,
          error: "You are not authorized to access this page."
      end
    end

end

app/controllers/backoffice_controller.rb
class BackofficeController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  layout 'backoffice'

  private

  def authorize_admins!
    redirect_to backoffice_case_studies_path unless current_user.is_admin?
  end
end

app/views/backoffice/pages/_create_form.html.slim
.form-row
  = f.input :title

- if @page.page_type == PageType::TEXT
  .form-row
    = f.input :body, input_html: {class:"-large"}

  .form-row.file-image
    = render 'backoffice/partials/input_image_file',
      f: f,
      name: :background,
      image: @page.background,
      class_name: "-large",
      custom_label:'background',
      size_recommendations: '600x400'

- else
  .form-row.file-map-input.file-map-upload
    = f.label :file
      = f.simple_fields_for :data_layers do |d|
        -if @page.page_type == PageType::TIMELINE
          .form-row
            = d.input :year, required: true

        #filename
        .form-row
          #input-file-wrapper.input-file-wrapper.input-wrapper.-lg
            = d.input :shapefile, as: :file, input_html: { id: 'map_file' }
            .placeholder
              span.title =t('drop_new_shapefile')
              span.sub-title
                =t('or')
                span.link =t('browse')

= f.hidden_field :page_type
.footer.-fixed
  .wrap: .row: .grid-sm-6.offset-sm-3
    .actions
      = f.button :submit, class: 'btn', id:'saveBtn'

app/views/backoffice/pages/_data_layer_fields.html.slim
- if @page.page_type == PageType::TIMELINE
  .nested-fields
    .row.file.-input
      .grid-sm-9
        = f.input :shapefile, as: :file, accept: ".csv", input_html: {id:"map_file"}
      .grid-sm-2.year
        label
          abbr title="required" *
        = f.input_field :year, placeholder: "Year", required: true
      .grid-sm-1
        = link_to_remove_association '×', f, class: 'btn -delete'
- else
  .nested-fields
    #filename
    #input-file-wrapper.input-file-wrapper.input-wrapper.-lg
      = f.input :shapefile, as: :file, input_html: { id: 'map_file' }
      .placeholder
        span.title =t('drop_shapefile')
        span.sub-title
          =t('or')
          span.link =t('browse')

app/views/backoffice/pages/_form.html.slim
- palettes = 2
- palette_range = 8

.form-row
  = f.input :title

- if params[:type].to_i == 1
  .form-row
    = f.input :body_first
  
  .form-row
    = f.input :body_second
    
  .form-row
    = f.input :body_thirth
    
  .form-row
    = f.label :background
    = f.input_field :background,
      class: @page.background.present? ? '_has_file' : nil, 
      style: @page.background.present? ? "background-image: url(#{@page.background.url(:medium)})" : nil

- else
  .form-row.file-map-input
    = f.label :file
    #filename.filename-selected data-filename= @page.data_layer.table_name
      p.name = @page.data_layer[:table_name]
    .input-wrapper._hidden
      = f.input_field :file, as: :file, accept: ".csv", data: {filename: @page.data_layer.table_name}
      .placeholder =t ('new_shapefile')
    .list-container
      = f.label :column_selected
      = f.input_field :column_selected, as: :hidden, value: (@page.data_layer[:column_selected] or nil), class: 'input'
      #map-columns-list.box-list
    / = f.simple_fields_for :data_layer do |c|
    /   = render 'data_layer_fields', f: c
    / = link_to_add_association t('add_data_layers'), f, :data_layer, class: 'btn -dotted'
  
  / .form-row
  /   = f.label :map_column
  /   = f.input_field :map_column, as: :radio_buttons

  
    
  .form-row
    = f.label :color_palette
    .box-selector
      - for t in 1..palettes
        .item.-col-2.-palette data-value="#{t}" class="-range-#{t} #{@page.color_palette.to_i == t ? '_selected' : nil}"
          - for r in 1..palette_range
            .range
              span.-bordered
              span
      = f.input_field :color_palette, as: :hidden, value: (@page.color_palette.to_i or 1), class: 'input'
  / .form-row#customPalette class="#{@page.color_palette.nil? ? nil : '_hidden'}"
  /   = f.input :custom_color_palette
  
  .form-row
    = f.association :charts, as: :check_boxes
    
  .form-row
    = f.simple_fields_for :interest_points do |c|
      = render 'interest_point_fields', f: c
    = link_to_add_association t('add_interest_points'), f, :interest_points, class: 'btn -dotted'

= f.hidden_field :page_type, value: params[:type]
= f.hidden_field :case_study_id, value: params[:case_study_id]

.form-row._center
  - if @page[:id]
    = link_to t('delete'), backoffice_case_study_page_path(case_study_id: params[:case_study_id], id: @page[:id]),  method: :delete, data: { confirm: t('confirm_sure') }, class: 'btn -primary -alt'
  = f.button :submit, class: 'btn -primary'

app/views/backoffice/pages/_form_new.html.slim
.form-row
  = f.input :title

- if params[:type].to_i == 1
  .form-row
    = f.input :body_first
  
  .form-row
    = f.input :body_second
    
  .form-row
    = f.input :body_thirth
    
  .form-row.file-image
    = render 'backoffice/partials/input_image_file', f: f, name: :background, image: @page.background, class_name: "-large", custom_label:'background'

- else
  .form-row.file-map-input
    = f.label :file
    #filename.filename-selected._hidden
      p.name
      span.close ×
    .input-wrapper.-lg
      = f.input_field :file, as: :file, accept: ".csv"
      .placeholder
        span.title =t('drop_shapefile')
        span.sub-title
          =t('or') 
          span.link =t('browse')

= f.hidden_field :page_type, value: params[:type]
= f.hidden_field :case_study_id, value: params[:case_study_id]

.form-row._center
  - if @page[:id]
    = link_to t('delete'), backoffice_case_study_page_path(case_study_id: params[:case_study_id], id: @page[:id]),  method: :delete, data: { confirm: t('confirm_sure') }, class: 'btn -primary -alt'
  = f.button :submit, class: 'btn -primary'

app/views/backoffice/pages/_interest_point_fields.html.slim
.nested-fields
  .row
    .grid-sm-4
      = f.input :name
    .grid-sm-2
      = f.input :lat
    .grid-sm-2
      = f.input :lng
    .grid-sm-3
      = f.input :radius, :label => 'Radius (km)'
    .grid-sm-1
      = link_to_remove_association '×', f, class: 'btn -delete'
    .grid-sm-12
      = f.input :description

app/views/backoffice/pages/edit.html.slim
section.l-main

  header.header
    .wrap: .row
      .grid-sm-8
        h1 = @case_study.title.truncate(50)
      .grid-sm-4._vcenter._right
        .btns-toolbar
          = link_to t('save'), '#save', class: 'btn', id: 'saveBtn'

  .content
    .wrap: .row
      .grid-sm-2
        = render partial: 'backoffice/partials/sidebar'

      #caseStudyPage.grid-sm-6.offset-sm-1 data-type= @page.page_type
        - layersUploading = false
        - layersError = false
        - feedbackMsg = ''
        - erroredLayer = nil
        - @page.data_layers.each do |d|
          - if [ImportStatus::PENDING, ImportStatus::UPLOADING].include?(d.import_status)
            - layersUploading = true
            - feedbackMsg = "Datasets files are being uploaded, please wait and page will reload automatically or return in a moment."
            - if d.import_attempt > 0
              - feedbackMsg = feedbackMsg + " Import started #{d.import_attempt} minutes ago. Larger files will take longer to import. The application will allow 1 hour before assuming a failure in the upload."
            - break
          - if d.import_status == ImportStatus::FAILURE
            - layersError = true
            - erroredLayer = d
            - feedbackMsg = 'There was an error uploading the file, please remove it and try again later'
            - break

        - if layersUploading || layersError
          .loading-container
            div class=(layersUploading ? '_is-loading':'')
              span.loading-msg = feedbackMsg
            - if layersError
              - if @page.data_layers.count > 1
                = link_to t('delete'), backoffice_data_layer_path(erroredLayer),
                  method: :delete, class: 'btn -alt'
              - else
                = link_to t('delete'),
                  backoffice_case_study_page_path(case_study_id: @page.case_study.id,
                  id: @page.id), method: :delete, class: 'btn -alt'
        - else
          = simple_form_for @page, url: backoffice_case_study_page_path, html: { multipart: true }, html: { class: "exit-saving"}  do |f|
            - if @page.page_type == PageType::TEXT
              = render 'backoffice/pages/edit_form/edit_form_text', f: f
            - elsif @page.page_type == PageType::TIMELINE
              - @page.data_layers = @page.data_layers.order("id")
              = render 'backoffice/pages/edit_form/edit_form_timeline', f: f
            - else 
              = render 'backoffice/pages/edit_form/edit_form_map', f: f

            = render 'backoffice/pages/edit_form/edit_form_footer', f: f
            / = render 'edit_form', f: f
          ._hidden
            #feedbackAnalyzing
              .loading-container
                div._is-loading
                  span.loading-msg
                  | The datalayers are being analyzed,
                    please wait a moment.

app/views/backoffice/pages/new.html.slim
section.l-main

  header.header
    .wrap: .row
      .grid-sm-8
        h1 = @case_study.title.truncate(50)
      .grid-sm-4._vcenter._right
        .btns-toolbar
          = link_to t('save'), '#save', class: 'btn', id: 'saveBtn'

  .content class="-cs-theme-#{@case_study.template}"
    .wrap: .row
      .grid-sm-2
        = render partial: 'backoffice/partials/sidebar'

      .grid-sm-6.offset-sm-1
        = simple_form_for @page, url: backoffice_case_study_pages_path, html: { multipart: true }, html: { class: "exit-saving"}  do |f|
          = render 'create_form', f: f