config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :backoffice do
    resources :case_studies, path: 'case-studies' do
      resources :pages, except: [:index, :show]
      resources :select_type, only: [:index]
      post 'duplicate', on: :member
    end

    resources :users, except: [:show]
    resources :organizations, except: [:show]

    resources :data_layers, path: "data-layers", only: [:destroy, :show]
    root 'case_studies#index', as: 'dashboard'
  end

  resources :case_studies, only: [:index, :show], param: :slug, path: 'case-studies' do
    get 'preview', on: :member
  end

  resources :tags, defaults: { format: 'json' }
  get '/tags', to: 'tags#index'

  resources :contact_form, only: [:create], path: "contact-form", defaults: { format: 'json' }

  get '/cases', to: redirect('/#cases')
  get '/contact-form', to: redirect('/#contact-form')

  root 'landing#index', as: 'root'

end

app/models/case_study.rb
class CaseStudy < ActiveRecord::Base

  default_scope { order('case_studies.created_at ASC') }
  scope :published, -> { where(published: true ) }

  before_validation :check_slug, on: [:create, :update]

  acts_as_taggable

  has_many :contacts, dependent: :destroy
  has_many :pages, dependent: :destroy
  has_many :valid_pages, -> {
    joins("LEFT OUTER JOIN data_layers ON data_layers.page_id = pages.id").
    distinct.includes(:charts, :interest_points).
    where("(data_layers.is_ready = 't' AND pages.page_type IN (?)) OR (pages.page_type = ?)",
          [PageType::TIMELINE, PageType::MAP], PageType::TEXT )},
    class_name: 'Page'

  belongs_to :organization
  has_attached_file :cover_image, styles: {
    medium: '385x200#',
    large: '1920x1080#'
  }

  validates :title, presence: true, length: { minimum: 2, maximum: 100 }
  validates_uniqueness_of :slug
  validates :lat, presence: true
  validates :lng, presence: true
  validates :template, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5
  }
  validates_inclusion_of :published, in: [true, false]
  validates_attachment_content_type :cover_image, content_type: /\Aimage\/.*\Z/

  accepts_nested_attributes_for :contacts, reject_if: :all_blank, allow_destroy: true

  attr_accessor :delete_image

  def delete_image= delete_image
    self.cover_image.clear if delete_image == "true"
  end

  def self.where_published(params)
    published.where(params)
  end

  def self.with_pages
    includes(:pages)
  end

  def self.clone(id)
    include_these = [
      :contacts,
      { pages: [ :interest_points, :data_layers, :charts ] }
    ]
    c_study = find(id).deep_clone(include: include_these) do |orig, kopy|
      kopy.slug = orig.slug+"-"+Time.now.to_i.to_s if kopy.respond_to?(:slug)
      kopy.cloning = true if kopy.respond_to?(:file)
      kopy.cover_image = orig.cover_image if kopy.respond_to?(:cover_image)
      kopy.background = orig.background if kopy.respond_to?(:background)
      kopy.logo = orig.logo if kopy.respond_to?(:logo)
    end
    c_study
  end

  def self.get_tag_filtered(options={})
    case_studies = CaseStudy.all
    case_studies = case_studies.tagged_with(options[:tags]) if options[:tags]
    case_studies
  end

  def self.search(search)
    where("title ILIKE ?", "%#{search}%")
  end

private
  def check_slug
    if self.slug.blank?
      self.slug = self.title.parameterize
    end
  end


end

app/controllers/backoffice/case_studies_controller.rb
class Backoffice::CaseStudiesController < BackofficeController

  before_action :set_case_study, only: [:show, :edit, :update, :destroy]
  before_action :set_existing_contacts, only: [:new, :edit]
  before_action :restrict_access!, only: [:edit, :update, :destroy]

  def index
    @case_studies = if current_user.is_admin?
                      CaseStudy.all
                    elsif current_user.organization.nil?
                      CaseStudy.where(organization_id: nil)
                    else
                      current_user.organization.try(:case_studies) || []
                    end
  end

  def show
    redirect_to edit_backoffice_case_study_path(@case_study)
  end

  def new
    @case_study = CaseStudy.new
    @contacts = @case_study.contacts.build
  end

  def edit
    @contacts = @case_study.contacts.presence || @case_study.contacts.build
  end

  def create
    @case_study = CaseStudy.new(case_studies_params)
    if @case_study.save
      redirect_to edit_backoffice_case_study_path(@case_study),
        notice: 'Case study created successfully.'
    else
      set_existing_contacts
      render :new
    end
  end

  def update
    if @case_study.update(case_studies_params)
      redirect_to [:backoffice, @case_study],
        notice: 'Case study updated successfully.'
    else
      set_existing_contacts
      render :edit
    end
  end

  def destroy
    @case_study.destroy
    redirect_to backoffice_case_studies_path,
      notice: 'Case study deleted successfully.'
  end

  def duplicate
    @case_study = CaseStudy.clone(params[:id])
    if @case_study.save
      redirect_to edit_backoffice_case_study_path(@case_study),
        notice: 'Case study duplicated successfully.'
    else
      redirect_to request.referrer || backoffice_dashboard_path,
        alert: 'Case study duplication failed.'
    end
  end

  private

    def set_case_study
      @case_study = CaseStudy.find(params[:id])
    end

    def set_existing_contacts
      @existing_contacts = Contact.all.where.not(logo_file_name: nil).to_a
      @existing_contacts.uniq!{|c| c.logo_file_name}
    end

    def case_studies_params
      params.require(:case_study).permit(
        :title,
        :slug,
        :description,
        :published,
        :lat,
        :lng,
        :template,
        :cover_image,
        :tag_list,
        :delete_image,
        contacts_attributes: [:id, :body, :logo, :website, :_destroy,
          :delete_image, :logo_from_contact_id]
      )
    end

    def restrict_access!
      unless current_user.is_admin? || current_user.can_manage?(@case_study)
        redirect_to backoffice_case_studies_path,
          error: "You can only manage your Organization's case studies."
      end
    end

end

app/controllers/backoffice/data_layers_controller.rb
class Backoffice::DataLayersController < BackofficeController

  before_action :set_data_layer, only: [:show, :destroy]

  respond_to :json

  def show
    body = @data_layer ||
      { error:'400', msg: 'You need to provide an id', data_layer:{}}
    render json: body
  end

  def destroy
    @page = @data_layer.page
    @data_layer.destroy
    respond_to do |format|
      format.json { render json: true }
      format.html { redirect_to edit_backoffice_case_study_page_path(@page.case_study, @page) }
    end
  end


  private

  def set_data_layer
    @data_layer = DataLayer.find(params[:id])
  end
end

app/controllers/backoffice/organizations_controller.rb
class Backoffice::OrganizationsController < BackofficeController

  before_action :set_organization, only: [:edit, :update, :destroy]
  before_action :authorize_admins!

  def index
    @organizations = Organization.all
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organizations_params)
    if @organization.save
      redirect_to backoffice_organizations_path,
        notice: 'Organization created successfully'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @organization.update(organizations_params)
      redirect_to backoffice_organizations_path,
        notice: 'Organization updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @organization.destroy
    redirect_to backoffice_organizations_path,
      notice: 'Organization deleted successfully'
  end

  private

  def set_organization
    @organization = Organization.find(params[:id])
  end

  def organizations_params
    params.require(:organization).permit(:name)
  end
end

app/controllers/backoffice/pages_controller.rb
class Backoffice::PagesController < BackofficeController

  before_action :set_case_study, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_page, only: [:edit, :update, :destroy]
  before_action :set_charts, only: [:new, :edit]

  def new
    @page = @case_study.pages.new(page_type: params[:type])
    @page.data_layers.build
  end

  def create
    @page = @case_study.pages.new(page_params)
    if @page.save

      upload_pending_files

      redirect_to edit_backoffice_case_study_page_path(
        @case_study, @page,
          type: @page.page_type,
          shapefile: nil
      ), notice: 'Page created successfully.'
    else
      @page.data_layers.build if @page.data_layers.empty?
      set_charts
      render :new
    end
  end

  def edit
    gon.cartodb_user = ENV["CDB_USERNAME"]
    gon.case_study = @case_study.to_json
    gon.page = @page.to_json(include: :data_layers)
  end

  def update
    if @page.update(page_params)

      upload_pending_files

      redirect_to edit_backoffice_case_study_page_path(
        @case_study, @page, type: @page.page_type
      ), notice: 'Page updated successfully.'
    else
      @page.data_layers.build if @page.data_layers.empty?
      gon.cartodb_user = ENV["CDB_USERNAME"]
      gon.case_study = @case_study.to_json
      gon.page = @page.to_json(include: :data_layers)
      set_charts
      render :edit
    end
  end

  def destroy
    @page.destroy
    redirect_to edit_backoffice_case_study_path(@case_study),
      notice: 'Page deleted successfully.'
  end

  private

    def upload_pending_files
      @page.data_layers.each do |d|
        Resque.enqueue(CartoDbImporter, d.id) if d.import_status == ImportStatus::PENDING
      end
    end

    def set_case_study
      @case_study = CaseStudy.find(params[:case_study_id])
    end

    def set_page
      @page = Page.find(params[:id])
    end

    def set_charts
      @charts = Chart.all
    end

    def page_params
      params.require(:page).permit(
        :title,
        :basemap,
        :basemap_url,
        :body,
        :background,
        :color_palette,
        :custom_basemap,
        :page_type,
        :chart_type_list,
        :case_study_id,
        :column_selected,
        :delete_image,
        data_layers_attributes: [
          :id,
          :table_name,
          :year,
          :shapefile,
          :layer_column,
          :layer_column_alias,
          :raster_color_input,
          :raster_type,
          :raster_categories,
          :custom_columns_colors
        ],
        interest_points_attributes: [:id, :name, :lat, :lng, :radius, :_destroy, :description],
        chart_ids: []
      )
    end

end

app/controllers/backoffice/select_type_controller.rb
class Backoffice::SelectTypeController < BackofficeController

  def index
    @case_study = CaseStudy.find(params[:case_study_id])
  end

end

app/controllers/backoffice/users_controller.rb
class Backoffice::UsersController < BackofficeController

  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :set_organizations, only: [:edit, :new]
  before_action :set_change_pwd, only: [:edit, :update]
  before_action :restrict_access!, only: [:edit, :update, :destroy]

  def index
    @users = User.all.order(:email)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to backoffice_users_path,
        notice: 'User created successfully.'
    else
      set_organizations
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to backoffice_users_path,
        notice: 'User updated successfully.'
    else
      set_organizations
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to backoffice_users_path, notice: 'Page deleted successfully.'
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit!
    end

    def set_organizations
      @organizations = Organization.all
    end

    def set_change_pwd
      @change_pwd = params[:change_pwd].presence || false
    end

    def restrict_access!
      unless current_user.is_admin? || current_user == @user
        redirect_to backoffice_users_path,
          error: "You are not authorized to access this page."
      end
    end

end

app/controllers/backoffice_controller.rb
class BackofficeController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  layout 'backoffice'

  private

  def authorize_admins!
    redirect_to backoffice_case_studies_path unless current_user.is_admin?
  end
end

app/controllers/case_studies_controller.rb
class CaseStudiesController < ApplicationController

  before_action :restrict_access!, only: [:index]
  after_action :check_case_study

  def index
    if case_studies_params[:search]
      @case_study = CaseStudy.published.search(case_studies_params[:search])
      render json: @case_study
    elsif case_studies_params[:tags]
      @case_study = CaseStudy.published.get_tag_filtered(case_studies_params).limit(9)
      render json: @case_study
    else
      @case_study = CaseStudy.published.limit(9)
      render json: @case_study
    end
  end

  def show
    @tags = Tag.all
    @case_study = CaseStudy.published.where(slug: params[:slug]).first
    @tab = params[:tab]

    gon.case_study = @case_study.
      as_json(include: [:contacts, {valid_pages: {include: [:data_layers, :charts, :interest_points]}}])
    gon.cartodb_user = ENV["CDB_USERNAME"]
  end

  def preview
    if user_signed_in?
      @tags = Tag.all
      @case_study = CaseStudy.where(slug: params[:slug]).first

      gon.case_study = @case_study.
        as_json(include: [:contacts, {valid_pages: {include: [:data_layers, :charts, :interest_points]}}])
      gon.cartodb_user = ENV["CDB_USERNAME"]
    else
      not_found
    end
  end

  private

    def check_case_study
      unless @case_study
        not_found
      end
    end

    def case_studies_params
      params.permit(:search, tags:[])
    end

    def restrict_access!
      redirect_to backoffice_dashboard_path unless user_signed_in?
    end

end

app/views/backoffice/case_studies/_contact_fields.html.slim
.nested-fields
  .row
    .grid-sm-7
      = f.input :body, label: false, placeholder: t('simple_form.placeholders.contact.body')
    .grid-sm-4
      = render 'backoffice/partials/input_image_file', f: f, name: :logo, image: f.object.logo, placeholder_title:'', placeholder_subtitle:'Select Logo', class_name:'-sm'
      a.btn.-dotted.-light.logos-ftlight href="#" data={ id: f.object.id, featherlight:"#logos"} Uploaded logos
    .grid-sm-1
      = link_to_remove_association '×', f, class: 'btn -delete'
    .grid-sm-11
      = f.input :website, label: false, placeholder: t('simple_form.placeholders.contact.website')
  = f.input :id, as: :hidden
  = f.hidden_field :logo_from_contact_id, id: "contact-id-#{f.object.id}"

app/views/backoffice/case_studies/_contacts_fields.html.slim
.nested-fields
  .row
    .grid-sm-7
      = f.input :body, label: false, placeholder: t('simple_form.placeholders.contact.body')
    .grid-sm-4
      = render 'backoffice/partials/input_image_file', f: f, name: :logo, image: f.object.logo, placeholder_title:'', placeholder_subtitle:'Select Logo', class_name:'-sm'
      a.btn.-dotted.-light.logos-ftlight href="#" data={ id: f.object.id, featherlight:"#logos"} Uploaded logos
    .grid-sm-1
      = link_to_remove_association '×', f, class: 'btn -delete'
    .grid-sm-11
      = f.input :website, label: false, placeholder: t('simple_form.placeholders.contact.website')
  = f.input :id, as: :hidden
  = f.hidden_field :logo_from_contact_id, id: "contact-id-#{f.object.id}"

app/views/backoffice/case_studies/_form.html.slim
- templates = 4

.form-row
  = f.input :title, input_html: { maxlength: 100 }

.form-row
  = f.input :slug, label:'Slug (Short title page in the url)', placeholder: @case_study.slug.blank? ? '' : @case_study.slug

.form-row
  = f.input :published, as: :radio_buttons, collection: [[t('published'), true], [t('unpublished'), false]]

.nested-fields
  .row
    .grid-sm-12
      = f.label :location
    .grid-sm-6
      = f.input :lat, wrapper_html: {class: "input-inline"}
    .grid-sm-6
      = f.input :lng, wrapper_html: {class: "input-inline"}

.form-row
  = f.input :tag_list, input_html: { class: 'tags', value: f.object.tag_list.to_s }

.form-row
  = f.label :contacts

  - @item_index = 0
  = f.simple_fields_for :contacts do |c|
    = render 'contacts_fields', f: c
    - @item_index += 1
  div#addContact
    = link_to_add_association t('add_contact'), f, :contacts, class: 'btn -dotted'

.form-row
  = f.label :template
  .box-selector
    - for t in 1..templates
      .item.-col-2 data-value="#{t}" class="#{@case_study.template.to_i == t ? '_selected' : nil}"
        = image_tag "template-#{t}.jpg"
        a.icon href="#" data-featherlight= image_path("template-#{t}.jpg")
          svg.icon-zoom-in
            use xlink:href="#icon-zoom-in"
    = f.input_field :template, as: :hidden, value: (@case_study.template.to_i or 1), class: 'input'

.form-row
  = render 'backoffice/partials/input_image_file', f: f, 
    name: :cover_image, 
    image: @case_study.cover_image, 
    class_name: '-large', 
    custom_label: 'thumbnail',
    size_recommendations: '600x400'
  

.footer.-fixed
  .wrap: .row: .grid-sm-6.offset-sm-3
    .actions
      = f.button :submit, class: 'btn', id: "saveBtn"
      
._hidden
  #logos.wrap
    - if @existing_contacts.blank?
      p = t('no_logos_uploaded')
    - else 
      .row
        h1.title SELECT LOGO
      .row
        - @existing_contacts.each do |c|
          .uploaded-images
            = image_tag c.logo.url(:medium), data: { contact: c.id }

app/views/backoffice/case_studies/_input_file.html.slim
- placeholder_title = placeholder_title ? placeholder_title : 'Drop an image file here'
- placeholder_subtitle = placeholder_subtitle ? placeholder_subtitle : 'or <span class="link">browse'

- class_name = class_name ? class_name : nil

- input_style = image.exists? ? "background-image: url(#{image})" : nil
- input_class = image.exists? ? "_has_file" : nil
.file-image-input class= "#{class_name} #{input_class}"
  = f.input name, as: :file, label: false, wrapper_html: {style: input_style}
  .placeholder
    span.title = placeholder_title.html_safe
    span.sub-title = placeholder_subtitle.html_safe
  span.close ×

app/views/backoffice/case_studies/edit.html.slim
section.l-main

  header.header
    .wrap: .row
      .grid-sm-8
        h1 = @case_study.title.truncate(50)

      .grid-sm-4._vcenter._right
        .btns-toolbar
          = link_to t('preview'), preview_case_study_path(@case_study.slug), class: 'btn', target: '_blank'
          = link_to t('save'), '#save', class: 'btn', id: 'saveBtn'
          
          - if @case_study.published
            = link_to t('unpublish'), backoffice_case_study_path( @case_study, case_study: {published: false} ), method: :patch, class: 'btn'
          - else 
            = link_to t('publish'), backoffice_case_study_path( @case_study, case_study: {published: true} ), method: :patch, class: 'btn'
          
          = link_to t('delete'), backoffice_case_study_path(@case_study),  method: :delete, data: { confirm: t('confirm_sure') }, class: 'btn'
  
  .content
    .wrap: .row
      .grid-sm-2
        = render partial: 'backoffice/partials/sidebar'

      .grid-sm-6.offset-sm-1
        = simple_form_for @case_study, url: backoffice_case_study_path, html: { multipart: true }, html: { class: "exit-saving"} do |f|
          = render 'form', f: f

app/views/backoffice/case_studies/index.html.slim
.l-main
  .wrap
    .row
      .grid-xs-12.grid-sm-12
        h1.-big = t 'case_studies'

    .row
      - for case_study in @case_studies
      
        - class_name = "thumbnail #{'_unpublished' unless case_study.published}"
        - bg_image = case_study.cover_image.present? ? "background-image: url(#{case_study.cover_image.url(:medium)})" : nil
        
        .grid-xs-12.grid-sm-6.grid-md-4 class= class_name
          
          = link_to edit_backoffice_case_study_path(case_study), class: 'content' do

            .thumb style= bg_image
            .caption
              - if !case_study.published
                  span.caption-item.-secondary._upper = t 'unpublished'
              p.caption-item = case_study.title
              span.caption-item.-secondary
                | #{t('last_update')}: 
                time = l(case_study.updated_at.to_date, format: :short)
          .actions
            .container
              = link_to duplicate_backoffice_case_study_path(case_study), method: :post, class: 'action' do 
                svg.icon.icon-duplicate
                  use xlink:href="#icon-duplicate"
                span.description = t('duplicate')
              = link_to backoffice_case_study_path(case_study),  method: :delete, data: { confirm: t('confirm_sure') }, class: 'action' do 
                svg.icon.icon-delete
                  use xlink:href="#icon-delete"
                span.description = t('delete')
              - if !case_study.published
                = link_to backoffice_case_study_path( case_study, case_study: {published: true} ), method: :patch, class: 'action' do
                  svg.icon.icon-publish
                    use xlink:href="#icon-publish"
                  span.description = t('publish')
              - else 
                = link_to backoffice_case_study_path( case_study, case_study: {published: false} ), method: :patch, class: 'action' do 
                  svg.icon.icon-publish
                    use xlink:href="#icon-publish"
                  span.description = t('unpublish')
        
      .grid-xs-12.grid-sm-6.grid-md-4

        = link_to new_backoffice_case_study_path, class: 'btn -add -thumbnail' do

          span.label = t('add_new_case_study')

app/views/backoffice/case_studies/new.html.slim
section.l-main

  header.header
    .wrap: .row
      .grid-sm-8
        h1 = t 'create_case_study'

      .grid-sm-4._vcenter._right
        .btns-toolbar
          = link_to t('save'), '#save', class: 'btn', id: 'saveBtn'
  
  .content
    .wrap: .row
      .grid-sm-6.offset-sm-3
        = simple_form_for @case_study, url: backoffice_case_studies_path, html: { multipart: true }, html: { class: "exit-saving"}  do |f|
          = render 'form', f: f